### PR TITLE
Implement CORS middleware

### LINKED ISSUE #16: add cors

### PR DESCRIPTION
**Pull request by firateski**
Resolves #16

### CODE REVIEW

**Comment by mstrYoda** [comment]
Thank you for your contribution, can you take a look to router's global option handler and decide wether to use custom function or internal middleware support?

https://github.com/julienschmidt/httprouter#automatic-options-responses-and-cors

**Comment by firateski** [comment]
The `GlobalOPTIONS` handler of the `httprouter` library is not the thing we're looking for as I understand from this documentation. `GlobalOPTIONS` is just a common handler for `OPTIONS` type HTTP requests.

Please let me know if I wrong, I can recheck it so I can make the needed changes.

Edit: Do browsers use `OPTIONS` HTTP requests to retrieve information about CORS too? if the answer is yes then it's better to use this `GlobalOPTIONS` handler.

**Comment by firateski** [comment]
I just wrote a simple script that makes a simple GET request to our API to test the `GlobalOPTIONS` handler and it didn't work due to CORS policy. I think my current implementation is fine for now to go.

**Review by mstrYoda — APPROVED** [review]

**Comment by mstrYoda** [comment]
Thank you for your contribution 👍

**Pull request merged**
